// per4_vue_sm/src/App.vue
<template>
  <h1>Dengan State Management (Pinia)</h1>
  <HitungDisplay />
  <HitungButton />
  <ResetButton />
  <HistoryList />
</template>

<script>
import HitungDisplay from "./components/HitungDisplay.vue";
import HitungButton from "./components/HitungButton.vue";
import ResetButton from "./components/ResetButton.vue";
import HistoryList from "./components/HistoryList.vue";

export default {
  name: "App",
  components: {
    HitungDisplay,
    HitungButton,
    ResetButton,
    HistoryList
  }
}
</script>

// per4_react_sm/src/App.js
import React from "react";
import { CounterProvider } from "./context/HitungContext";
import CounterDisplay from "./components/HitungDisplay";
import CounterButton from "./components/HitungButton";
import ResetButton from "./components/ResetButton";
import HistoryList from "./components/HistoryList";

function App() {
  return (
    <CounterProvider>
      <h1>Dengan State Management (Context API)</h1>
      <CounterDisplay />
      <CounterButton />
      <ResetButton />
      <HistoryList />
    </CounterProvider>
 );
}

export default App;
