// per4_tugas_react_sm/src/App.js
import React from "react";
import { CatatanProvider } from "./context/CatatanContext";
import TambahCatatan from "./components/TambahCatatan";
import DaftarCatatan from "./components/DaftarCatatan";
import JumlahCatatan from "./components/JumlahCatatan";
import HapusSemua from "./components/HapusSemua";
import CariCatatan from "./components/CariCatatan";

function App() {
  return (
    <CatatanProvider>
      <div>
        <h1>Catatan Sederhana - React + Context API</h1>
        <TambahCatatan />
        <CariCatatan />
        <JumlahCatatan />
        <HapusSemua />
        <DaftarCatatan />
      </div>
    </CatatanProvider>
  );
}

export default App;

// per4_tugas_vue_sm/src/App.vue
<template>
  <div>
    <h1>Catatan Sederhana - Vue + Pinia</h1>
    <TambahCatatan />
    <CariCatatan />
    <JumlahCatatan />
    <HapusSemua />
    <DaftarCatatan />
  </div>
</template>

<script>
import TambahCatatan from "./components/TambahCatatan.vue";
import DaftarCatatan from "./components/DaftarCatatan.vue";
import JumlahCatatan from "./components/JumlahCatatan.vue";
import HapusSemua from "./components/HapusSemua.vue";
import CariCatatan from "./components/CariCatatan.vue";

export default {
  name: "App",
  components: {
    TambahCatatan,
    DaftarCatatan,
    JumlahCatatan,
    HapusSemua,
    CariCatatan
  }
};
</script>
