// per3_react_tugas/src/components/Button.js
import React from "react";

const Button = ({ tampilkan, onToggle }) => {
    return (
        <div>
            <button 
            style={{
                backgroundColor: tampilkan ? "green" : "red",
                color: "white",
                padding: "10px 20px",
                border: "none",
                borderRadius: "5px",
                cursor: "pointer",
                fontSize: "16px"
            }}
            onClick={onToggle}>
                {tampilkan ? "Sembunyikan Card" : "Tampilkan Card"}
            </button>
        </div>
    );
};

export default Button;

// per3_vue_tugas/src/components/ButtonComponent.vue
<template>
    <div>
        <button 
            @click="$emit('toggle')"
            :style="{ 
                backgroundColor: tampilkan ? 'green' : 'red',
                color: 'white',
                padding: '10px 20px',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer',
                fontSize: '16px'
            }">
            {{ tampilkan ? 'Sembunyikan Card' : 'Tampilkan Card' }}
        </button>
    </div>
</template>

<script>
export default {
    name: 'ButtonComponent',
    props: {
        tampilkan: Boolean
    },
    emits: ['toggle']
}
</script>
