// per3_vue_tugas/src/components/HeaderComponent.vue
<template>
    <div :style="{ 
        textAlign: 'center'
    }">
        <h1>Daftar Film Saya</h1>
        <p style="font-size: 14px; color: #555">
            {{ tampilkan ? 'Card Ditampilkan' : 'Card Disembunyikan' }}
        </p>
    </div>
</template>

<script>
export default {
    name: 'HeaderComponent',
    props: {
        tampilkan: Boolean
    }
}
</script>

// per3_react_tugas/src/components/Header.js
import React from "react";

const Header = ({ tampilkan }) => {
    return (
        <div style={{ 
            textAlign: "center"
        }}>
            <h1>Daftar Film Saya</h1>
            <p style={{ fontSize: "14px", color: "#555" }}>
                {tampilkan ? "Card Ditampilkan" : "Card Disembunyikan"}
            </p>
        </div>
    );
};

export default Header;
