// per4_tugas_react_sm/src/components/CariCatatan.js
import { useContext } from "react";
import { CatatanContext } from "../context/CatatanContext";

const CariCatatan = () => {
    const { cari, setCari } = useContext(CatatanContext);

    return (
        <input
            value={cari}
            onChange={(e) => setCari(e.target.value)}
            placeholder="Cari catatan..."
        />
    );
};

export default CariCatatan;

// per4_tugas_vue_sm/src/components/CariCatatan.vue
<template>
  <input
    :value="store.cari"
    @input="store.setCari($event.target.value)"
    placeholder="Cari catatan..."
  />
</template>

<script>
import { useCatatanStore } from "../stores/Catatan";

export default {
  setup() {
    const store = useCatatanStore();
    return { store };
  }
};
</script>
