// per4_tugas_react_sm/src/components/DaftarCatatan.js
import { useContext } from "react";
import { CatatanContext } from "../context/CatatanContext";

const DaftarCatatan = () => {
    const { catatanFiltered } = useContext(CatatanContext);

    return (
        <div>
            {catatanFiltered.length === 0 && <p>Belum ada catatan.</p>}
            <ul>
                {catatanFiltered.map((item, i) => (
                    <li key={i}>{item}</li>
                ))}
            </ul>
        </div>
    );
};

export default DaftarCatatan;

// per4_tugas_vue_sm/src/components/DaftarCatatan.vue
<template>
  <ul>
    <li v-for="(item, i) in store.catatanFiltered" :key="i">{{ item }}</li>
  </ul>
  <p v-if="store.catatanFiltered.length === 0">Belum ada catatan.</p>
</template>

<script>
import { useCatatanStore } from "../stores/Catatan";

export default {
  setup() {
    const store = useCatatanStore();
    return { store };
  }
};
</script>
