// per4_tugas_react_sm/src/components/TambahCatatan.js
import { useContext, useState } from "react";
import { CatatanContext } from "../context/CatatanContext";

const TambahCatatan = () => {
    const { tambah } = useContext(CatatanContext);
    const [teks, setTeks] = useState("");

    const handleTambah = () => {
        if (teks.trim()) {
            tambah(teks.trim());
            setTeks("");
        }
    };

    return (
        <div>
            <input
                value={teks}
                onChange={(e) => setTeks(e.target.value)}
                onKeyUp={(e) => e.key === "Enter" && handleTambah()}
                placeholder="Tulis catatan..."
            />
            <button onClick={handleTambah}>Tambah</button>
        </div>
    );
};

export default TambahCatatan;

// per4_tugas_vue_sm/src/components/TambahCatatan.vue
<template>
  <div>
    <input v-model="teks" @keyup.enter="tambah" placeholder="Tulis catatan..." />
    <button @click="tambah">Tambah</button>
  </div>
</template>

<script>
import { useCatatanStore } from "../stores/Catatan";
import { ref } from "vue";

export default {
  setup() {
    const store = useCatatanStore();
    const teks = ref("");
    const tambah = () => {
      if (teks.value.trim()) {
        store.tambah(teks.value.trim());
        teks.value = "";
      }
    };
    return { teks, tambah };
  }
};
</script>
