// per4_react_sm/src/components/HistoryList.js
import { useContext } from "react";
import { CounterContext } from "../context/HitungContext";

const HistoryList = () => {
    const { history } = useContext(CounterContext);
    return (
        <ul>
            {history.map((item, index) => (
                <li key={index}>Perubahan ke-{index + 1}: {item}</li>
            ))}
        </ul>
 );
};
export default HistoryList;

// per4_vue_sm/src/components/HistoryList.vue
<template>
    <div>
        <h3>Riwayat Perubahan</h3>
        <ul>
            <li v-for="(item, index) in counter.history" :key="index">Perubahan ke-{{ index + 1 }}: {{ item }}
            </li>
        </ul>
    </div>
</template>

<script>
import { useCounterStore } from "../stores/Hitung";
import { defineComponent } from "vue";

export default defineComponent({
    setup() {
        const counter = useCounterStore();
        return { counter };
    }
});
</script>
